### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#25]
- [ ] Add unit tests for the Frontend side
 - [ ] Add unit tests for the API
 - [ ] Add unit tests for the Tracking library
